dev:
    just run

run:
    zig build run

test:
    zig build test

cli *args:
    #!/usr/bin/env bash
    # nb: langnet-cli is out of project
    # we are relying on the devenv shell being set up
    cd .././../langnet-cli && devenv --quiet shell just -- cli {{args}}

cli-example:
    just cli query lat sedat --output json | nu -c 'cat | from json | to yaml'
    

