dev:
    just run

run:
    zig build run

test:
    zig build test

cli *args:
    #!/usr/bin/env bash
    # nb: langnet-cli is out of project
    # we are relying on the devenv shell being set up
    cd .././../langnet-cli && devenv --quiet shell just -- cli {{args}}

cli-example:
    just cli query lat sedat --output json | nu -c 'cat | from json | to yaml'

readme-zzz:
    curl https://raw.githubusercontent.com/tardy-org/zzz/refs/heads/main/docs/getting_started.md
    
install-zzz:
    zig fetch --save "git+https://github.com/tardy-org/zzz#v0.3.0-rc1"
